database: h2
spring:
  profiles:
    active: local
    include: real-oauth
  session:
    store-type: jdbc
  datasource:
    platform: h2
    data: classpath*:db/${database}/data.sql
    url: jdbc:h2:tcp://localhost/~/guhaedog
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
    initialization-mode: always
    sql-script-encoding: UTF-8
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create
  server:
    max-http-header-size: 30000



#spring:
#  profiles:
#    active: local
#    include: real-oauth
#  datasource:
#    platform: mysql
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1234
#    url: jdbc:mysql://localhost:3306/jpaexamplenk?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true&serverTimezone=UTC
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
#    generate-ddl: true
#
#    hibernate:
#      ddl-auto: update




